// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rpcapi/rpcapi.proto

/*
Package rpcapi is a generated protocol buffer package.

It is generated from these files:
	proto/rpcapi/rpcapi.proto

It has these top-level messages:
*/
package rpcapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "will/micro/example3/proto/model"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = model.SayResponse{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Order service

type OrderService interface {
	Hello(ctx context.Context, in *model.SayParam, opts ...client.CallOption) (*model.SayResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "rpcapi"
	}
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) Hello(ctx context.Context, in *model.SayParam, opts ...client.CallOption) (*model.SayResponse, error) {
	req := c.c.NewRequest(c.name, "Order.Hello", in)
	out := new(model.SayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	Hello(context.Context, *model.SayParam, *model.SayResponse) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		Hello(ctx context.Context, in *model.SayParam, out *model.SayResponse) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) Hello(ctx context.Context, in *model.SayParam, out *model.SayResponse) error {
	return h.OrderHandler.Hello(ctx, in, out)
}
