// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RespType int32

const (
	RespType_NONE    RespType = 0
	RespType_ASCEND  RespType = 1
	RespType_DESCEND RespType = 2
)

var RespType_name = map[int32]string{
	0: "NONE",
	1: "ASCEND",
	2: "DESCEND",
}

var RespType_value = map[string]int32{
	"NONE":    0,
	"ASCEND":  1,
	"DESCEND": 2,
}

func (x RespType) String() string {
	return proto.EnumName(RespType_name, int32(x))
}

func (RespType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

type CreateOrderParam struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderParam) Reset()         { *m = CreateOrderParam{} }
func (m *CreateOrderParam) String() string { return proto.CompactTextString(m) }
func (*CreateOrderParam) ProtoMessage()    {}
func (*CreateOrderParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *CreateOrderParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderParam.Unmarshal(m, b)
}
func (m *CreateOrderParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderParam.Marshal(b, m, deterministic)
}
func (m *CreateOrderParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderParam.Merge(m, src)
}
func (m *CreateOrderParam) XXX_Size() int {
	return xxx_messageInfo_CreateOrderParam.Size(m)
}
func (m *CreateOrderParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderParam.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderParam proto.InternalMessageInfo

func (m *CreateOrderParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Pair struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               string   `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{1}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Pair) GetValues() string {
	if m != nil {
		return m.Values
	}
	return ""
}

type CreateOrderResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// 数组
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// map
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 RespType         `protobuf:"varint,4,opt,name=type,proto3,enum=RespType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{2}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateOrderResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *CreateOrderResponse) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateOrderResponse) GetType() RespType {
	if m != nil {
		return m.Type
	}
	return RespType_NONE
}

func init() {
	proto.RegisterEnum("RespType", RespType_name, RespType_value)
	proto.RegisterType((*CreateOrderParam)(nil), "CreateOrderParam")
	proto.RegisterType((*Pair)(nil), "Pair")
	proto.RegisterType((*CreateOrderResponse)(nil), "CreateOrderResponse")
	proto.RegisterMapType((map[string]*Pair)(nil), "CreateOrderResponse.HeaderEntry")
}

func init() { proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8) }

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0xc7, 0x97, 0x7e, 0xb9, 0x9e, 0x80, 0x74, 0x51, 0xa4, 0x4c, 0x84, 0x52, 0xbc, 0x28, 0x82,
	0x51, 0xea, 0x4d, 0xf1, 0xca, 0xb1, 0x15, 0xbc, 0xea, 0x46, 0xf4, 0x05, 0x22, 0x3b, 0xa8, 0xe8,
	0xd6, 0x92, 0x56, 0xa1, 0xaf, 0xea, 0xd3, 0x48, 0xd2, 0x89, 0xd5, 0xf5, 0xee, 0x7c, 0xfc, 0xfb,
	0xe3, 0xfc, 0x1a, 0x98, 0x54, 0xaa, 0x6c, 0xca, 0xab, 0x52, 0xad, 0x51, 0x71, 0x53, 0xc7, 0xe7,
	0x10, 0xcc, 0x15, 0xca, 0x06, 0x97, 0x7a, 0xb8, 0x92, 0x4a, 0x6e, 0x58, 0x00, 0xf6, 0xa6, 0x7e,
	0x0e, 0x49, 0x44, 0x12, 0x5f, 0xe8, 0x32, 0xbe, 0x06, 0x67, 0x25, 0x5f, 0x95, 0xde, 0xbc, 0x61,
	0x6b, 0x36, 0xae, 0xd0, 0x25, 0x3b, 0x01, 0xef, 0x53, 0xbe, 0x7f, 0x60, 0x1d, 0x5a, 0x26, 0xbe,
	0xeb, 0xe2, 0x2f, 0x02, 0x47, 0x3d, 0xb0, 0xc0, 0xba, 0x2a, 0xb7, 0x35, 0xee, 0xb3, 0xff, 0x10,
	0xec, 0x5f, 0x02, 0xcb, 0xc0, 0x7b, 0x41, 0xb9, 0x46, 0x15, 0xda, 0x91, 0x9d, 0xd0, 0x34, 0xe2,
	0x03, 0x3c, 0x7e, 0x6f, 0x22, 0xf9, 0xb6, 0x51, 0xad, 0xd8, 0xe5, 0xd9, 0x19, 0x38, 0x4d, 0x5b,
	0x61, 0xe8, 0x44, 0x24, 0x39, 0x4c, 0x7d, 0xae, 0xc3, 0x8f, 0x6d, 0x85, 0xc2, 0x8c, 0xa7, 0x77,
	0x40, 0x7b, 0x5f, 0xf5, 0x9d, 0xfc, 0xce, 0xe9, 0x14, 0x5c, 0x73, 0x83, 0x51, 0xa2, 0xa9, 0xcb,
	0xb5, 0xbb, 0xe8, 0x66, 0xb7, 0x56, 0x46, 0x2e, 0x2e, 0x61, 0xfc, 0xc3, 0x64, 0x63, 0x70, 0x8a,
	0x65, 0x91, 0x07, 0x23, 0x06, 0xe0, 0xcd, 0x1e, 0xe6, 0x79, 0xb1, 0x08, 0x08, 0xa3, 0x70, 0xb0,
	0xc8, 0xbb, 0xc6, 0x4a, 0x67, 0xe0, 0x9a, 0xa3, 0x59, 0x06, 0xb4, 0xe7, 0xc0, 0x26, 0xfc, 0xff,
	0xaf, 0x9f, 0x1e, 0x0f, 0x49, 0xc6, 0xa3, 0x27, 0xcf, 0xbc, 0xd6, 0xcd, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x6b, 0x58, 0xe3, 0xc2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderParam, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *CreateOrderParam, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	CreateOrder(context.Context, *CreateOrderParam) (*CreateOrderResponse, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*CreateOrderParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/order.proto",
}
